dist: trusty
sudo: required

language:
  - cpp

compiler:
  - gcc

before_install:
  - sudo apt-get update

install:

  # PCL prebuilt binaries for trusty
  - sudo add-apt-repository ppa:v-launchpad-jochen-sprickerhof-de/pcl -y
  - sudo apt-get update
  - sudo apt-get install libpcl-dev -y

script:
  - mkdir build && cd build
  - cmake ..
  - make
  - ./pipeline ../examples/pipeline.yml ../examples/cloud.pcd