Pipeline:
    SurfaceNormalEstimation:
      strategy: approximations
      parameters:
        radius: 0.2
    KeypointDetection:
      strategy : sift
      parameters:
        minScale : 0.01f
        numberOfOctaves: 3
        numberOfScalesPerOctave: 4
        minContrast: 0.001f
    FeatureDescriptor:
      strategy: FPFH
      parameters:
        something: some
    Classification:
      strategy: KNN
      parameters:
        k: 20